# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "42 23 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: ""
          filename: assets/achivements.svg
          config_timezone: Europe/Paris
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X

      - name: Anilist
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: ""
          filename: assets/anilist.svg
          config_timezone: Europe/Paris
          plugin_anilist: yes
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, watching, characters
          plugin_anilist_shuffle: no
          plugin_anilist_user: HellsCrimson

      - name: General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata
          filename: assets/general.svg
          config_timezone: Europe/Paris
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_ignored: Mathematica, ShaderLab
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

      - name: Wakatime
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: ""
          filename: assets/wakatime.svg
          config_timezone: Europe/Paris
          plugin_wakatime: yes
          plugin_wakatime_days: 14
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os, os-graphs
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_url: https://wakapi.hellscrimson.eu
          plugin_wakatime_user: HellsCrimson

      - name: PageSpeed
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: ""
          filename: assets/page_speed.svg
          config_timezone: Europe/Paris
          plugin_pagespeed: true
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://www.hellscrimson.eu
          plugin_pagespeed_detailed: true

      - name: Fortune
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: ""
          filename: assets/fortune.svg
          config_timezone: Europe/Paris
          plugin_fortune: yes
  
  steam-box:
    name: Steam-Box
    runs-on: ubuntu-latest
    env:
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          STEAM_API_KEY: ${{ secrets.STEAM_API }}
          STEAM_ID: ${{ secrets.STEAM_ID }}
          UPDATE_OPTION: GIST_AND_MARKDOWN
          MARKDOWN_FILE: README.md
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        
      - name: Update-gist
        run: |-
            git clone https://github.com/HellsCrimson/steam-box.git 
            cd steam-box && go build -o steam ./cmd/box/main.go
            mv ./steam ../ && cd .. && rm -rf steam-box/
      
      - name: Commit and push
        run: |-
          ./steam
          git config --global user.email "bot@github.com" && git config --global user.name "Steam-Bot"
          git diff
          git add README.md && git commit -m ":memo: update profile" || exit 0
          git pull && git push
      
